### ISSUE TITLE
Block model gaps when highlighed

### ISSUE THREAD

**Issue by shoveln** [PianoManu/BlockCarpentry#16]
Forge: 32.0.108
BlockCarpentry: 1.16.1-0.3.1

When highlighting a block from this mod, the thin outline is transparent and makes the different model faces look like they don't connect correctly. Notice how the endstone is visible through the model outline.

![2020-10-11_18 02 46](https://user-images.githubusercontent.com/58153076/95692522-fa549780-0beb-11eb-92a7-2e8eb5800281.png)

In contrast, this is what the outline should look like.

![2020-10-11_18 03 25](https://user-images.githubusercontent.com/58153076/95692537-11938500-0bec-11eb-9fbd-c617f030ccb4.png)

**Comment by PianoManu** [comment]
Yup, that's because the blocks are rendered as translucent blocks, because otherwise glass or ice blocks would not be transparent anymore. I also know this bug, but I don't know how to fix it.

Strangely enough, I just tried to recreate it, and there is no gap anymore... 
![2020-10-15_18 43 21](https://user-images.githubusercontent.com/59123244/96160511-5bdf7380-0f16-11eb-9587-0007d2c94ff3.png)

Does it appear for every frame/illusion block or just for the full "cube"?
Regards, Manu

**Comment by PianoManu** [comment]
Does this problem still appear or is it solved?

**Comment by shoveln** [comment]
If I remember correctly, it was multiple blocks at the time. 

Using Forge 34.1.42 and BlockCarpentry 1.16.2-0.3.4, the gaps seem to be gone on everything. Sorry for the late response
