### ISSUE TITLE
Ladders Unclimbable

### ISSUE THREAD

**Issue by I-is-Zed** [PianoManu/BlockCarpentry#38]
Playing 1.16.5 and noticed after placing the frame ladder that they aren't climbable at all, blank or with a skin. They're definitely supposed to be, right? I thought it may have been Quark's enhanced ladders, but disabling those didn't have any effect.

Installed the mod by itself in a fresh profile and same thing, just can't climb it. Am I missing something?

**Comment by PianoManu** [comment]
Yeah I already noticed that... I don't know why, but sometimes, ladders don't work and to other times they work. I recognized it when I was playing Enigmatica 6, and I was pretty confused, because it worked for me, when I tried it with a fresh installation. Pretty weird, I don't know what causes it, it seems to appear somehow random. I'll fix this asap, but right now, I'm having a lot of work to do for my studies. Thanks for reporting!
Regards, Manu

**Comment by WenXin20** [comment]
Have you tried using the block tag `#minecraft:climbable`? Ladders, vines, and scaffolding all use this tag in 1.16.

**Comment by PianoManu** [comment]
No, I didn't think of it, I'll add the ladders to this tag. Thank you very much!

**Comment by WenXin20** [comment]
No problem!

**Comment by PianoManu** [comment]
I can't recreate this problem anymore (at least in [0.3.9](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry/files/3430443)), so I'll close this issue...
