### ISSUE TITLE
Crash when using Xaero's worldmap

### ISSUE THREAD

**Issue by Altrath** [PianoManu/BlockCarpentry#41]
+ Using:
- Forge 1.16.5 ver 36.1.25
- block carpentry ver 1.16-0.3.6
- OptiFine 1.16.5 HD U G8

+ Crash report:
https://pastebin.com/XXAwzGrQ

+ How to reproduce
Honestly, im not sure. It seems like applying blocks to illusion blocks causes a crash,
 its hit or miss tho, i could apply said block twice with no problem and then the third makes me crash. or after a restart it doesnt even cause a crash. All i can say is according to the crash report its a incompatibility between this mod and xaero's world map
 
 https://youtu.be/SMElvRUTlZ8 this is all i could get in the recording, but you can see that i applied a PURPUR PILLAR on a ladder and it didnt crash however a PURPUR BLOCK did, and you can see in the background many random block carpentry blocks when i was trying to reproduce the glitch and it DIDNT crash

**Comment by PianoManu** [comment]
Thanks for reporting! Sorry for not answering earlier, I'm having a lot of work right now. I already know that bug and I already fixed it (same error as in #39), it will be published with version 0.3.7 sometime soon. I've made a workaround, because I'm not really sure what causes these crashes. Anyway, thanks for reporting!
Regards, Manu

**Comment by PianoManu** [comment]
0.3.7 is out, so I'm closing this issue
