### ISSUE TITLE
[Bug] Rendering of Stairs

### ISSUE THREAD

**Issue by Romulus96** [PianoManu/BlockCarpentry#47]
In version 1.16 0.3.7. and 1.16 0.3.8. stairs have transparent holes that should be opaque after applying a texture to them. This bug was not present in version 1.16 0.3.6.

![2021-08-18_15 25 08](https://user-images.githubusercontent.com/89034933/129906506-3d9ef4a4-7067-4766-9dbf-8251919e7fd4.png)

## Technical Information

Minecraft 1.16
Forge 36.2.2
Optifine 1.16.5_HD_U_G8
BlockCarpentry 1.16-0.3.8

**Comment by PianoManu** [comment]
Yup, I already noticed it and I'm currently trying to fix that. Also, some parts of the textures have moved and some faces look weird. I wonder why, since I haven't touched the model files in a while and I only made transparency changes in the last update... Well, I'm trying my best to fix this soon...
Thanks for reporting!
Regards, Manu

**Comment by PianoManu** [comment]
Fixed with [0.3.9](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry/files/3430443)...
