### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Sunekaer** [PianoManu/BlockCarpentry#50]
https://paste.sunekaer.com/secosipoku.rb

**Comment by PianoManu** [comment]
Alright, I'm just plain stupid. I was in a hurry when I first tried to fix this issue (same issue as #46 and #49, hence the duplicate tag) and somehow got the client and dedicated server confused, and I didn't test it afterwards (because I thought I fixed it properly). So I ended up rendering the slab only on the server side... Welp...

Now I tested it completely on my test server and it works. It'll be fixed in the next update. Thanks for reporting!
Regards, Manu
