### ISSUE TITLE
Crashing on a dedicated server

### ISSUE THREAD

**Issue by Ephilem** [PianoManu/BlockCarpentry#63]
Hi! I would like using this mod in a dedicated server, but the mod is trying to access classes for a forge client (net.minecraft.client)

Here's the logs : https://crashy.net/efTy6pA2Z3KSautz81Pp
(Raw log) : https://pastebin.com/CjBJQRiw

Modpack that i'm using with the mod : https://www.curseforge.com/minecraft/modpacks/dimensions-dungeoneering/ (The modpack work in singleplayer)

**Comment by PianoManu** [comment]
It looks like Blockcarpentry doesn't like AstralSorcery's Ethereal Blocks. I'll look into that tomorrow. Thanks for reporting!
Regards, Manu

**Comment by PianoManu** [comment]
Alright, I found the problem (and it's a pretty obvious mistake I made soooo long ago it's a miracle no one has noticed that yet or got any crash), I'm already trying to fix it, but it might need some time because I want to validize my solution before releasing the fix...
Thanks again for reporting!
