### ISSUE TITLE
Blocks being removed from the hand in creative mode

### ISSUE THREAD

**Issue by TheDeviantCrafter** [PianoManu/BlockCarpentry#9]
While in creative mode, holding a block and right clicking on a framed block still takes that block out of the player's hand. The block should be copied and left in the hand instead.

**Comment by PianoManu** [comment]
Yup I know that. I decided to not change it (at least not now), because it would mean a huge rewrite. When I have enough time and all other important bugs are fixed, I'll change this behaviour. Maybe I'll do that for the next update. I don't know when this will be, because next week I'll continue studying, as the next semester begins. Regards, Manu

**Comment by PianoManu** [comment]
I have overcome myself and changed it this morning. I tested it in both survival and creative and it works fine now. I'll consider this as fixed and will close the issue now
